version: 2
jobs:
  test:
    environment:
      NPM_CONFIG_PREFIX: ~/.npm-global
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    # Restore the dependency cache
    - restore_cache:
        keys:
        - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
        - node-v1-{{ .Branch }}-
        - node-v1-
    - run: echo 'export PATH=$NPM_CONFIG_PREFIX:$PATH' >> $BASH_ENV
    - run: npm install --global bower polymer-cli
    - run: bower install
    - run: if [ -z "${NODE_ENV:-}" ]; then export NODE_ENV=test; fi
    - run: npm install
    # Save dependency cache
    - save_cache:
        key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
        paths:
        - ~/.npm-global
    - run: npm run build
  deploy:
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - run: ./deploy-to-production.sh
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
