version: 2
jobs:
  test:
    shell: /bin/bash --login
    docker:
    - image: circleci/node:8
      command: /sbin/init
    steps:
    - checkout
    # Restore the dependency cache
    - restore_cache:
        keys:
        - v1-npm-deps-{{ checksum "package-lock.json" }}
        - v1-npm-deps-
    - run: npm install --global bower polymer-cli
    - run: bower install
    - run: if [ -z "${NODE_ENV:-}" ]; then export NODE_ENV=test; fi
    - run: export PATH="~/TipoftheHats/new-tipofthehats.org/node_modules/.bin:$PATH"
    - run: npm install
    # Save dependency cache
    - save_cache:
        key: v1-npm-deps-{{ checksum "package-lock.json" }}
        paths:
        - ~/usr/local/lib/node_modules
    - run: npm run build
  deploy:
    shell: /bin/bash --login
    docker:
    - image: circleci/node:8
      command: /sbin/init
    steps:
    - checkout
    - run: ./deploy-to-production.sh
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
