version: 2
jobs:
  test:
    shell: /bin/bash --login
    docker:
    - image: circleci/node:8
      command: /sbin/init
    steps:
    - checkout
    # Restore the dependency cache
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-
        # Default branch if not
        - v1-dep-master-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1-dep-
    - run: npm install --global bower polymer-cli
    - run: bower install
    - run: if [ -z "${NODE_ENV:-}" ]; then export NODE_ENV=test; fi
    - run: export PATH="~/TipoftheHats/new-tipofthehats.org/node_modules/.bin:$PATH"
    - run: npm install
    # Save dependency cache
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.cache/bower
        - ~/usr/local/lib/node_modules
    - run: npm run build
  deploy:
    steps:
    - checkout
    - run: ./deploy-to-production.sh
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
