version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test & build
          command: npm build
